# Site settings
title: jGrunt - automatic component generating for Joomla CMS
email: michael@mp-development.de
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://pfitzer.github.io/jGrunt"
twitter_username: locopfitzer
github_username:  pfitzer

# Build settings
markdown: kramdown
permalink: pretty
